POST https://node-do-zero-qjvq.onrender.com/videos
Content-Type: application/json

{
    "title": "Video Render",
    "description": "Esse é o terceiro vídeo Render",
    "duration": 180

}

###

GET https://node-do-zero-qjvq.onrender.com/videos

###

GET https://node-do-zero-qjvq.onrender.com/videos?search=node

###

PUT https://node-do-zero-qjvq.onrender.com/videos/254ebc61-03b0-46de-ab53-03940d05360f
Content-Type: application/json

{
    "title": "Video Node",
    "description": "Video sobre NodeJS",
    "duration": 120

}

###

DELETE https://node-do-zero-qjvq.onrender.com/videos/c81571c2-4b38-4d9b-bb32-32e787cdd90c